openapi: 3.0.1
info:
  title: ZHistLex Text API
  version: 0.0.4
  license:
    name: GNU General Public License, version 2
    url: 'https://www.gnu.org/licenses/old-licenses/gpl-2.0.html'
  contact:
    name: ZHistLex – eHumanities Centre for Historical Lexikography (Work Package 2)
    url: 'http://zhistlex.de/'
  description: |
    # Overview
    
    This API specification describes the webservice for accessing source documents used by the ZHistLex project. 
    
servers:
  - url: 'http://zhistlex.de/api'
    description: ''
tags:
  - name: General Functions
    description: ''
  - name: Retrieving Content
    description: ''
paths:
  /:
    get:
      operationId: aboutInfo
      summary: |
        Provides general information about the API. Implementations are free to return e.g. version information of implementations or statistics about the data that is accessable through the API.
      tags:
        - General Functions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: ZHistLex Text API 0.0.1
            text/html:
              schema:
                type: string
                example: <html><title/>…</html>

  '/texts/{PPN}':
    get:
      operationId: isAvailable
      summary: |
        Provides general information about a text.
      tags:
        - Retrieving Content
      parameters:
        - $ref: '#/components/parameters/PPN'
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listOfSnippets'
        '404':
          $ref: '#/components/responses/resourceNotFound'


  '/texts/{PPN}/{location}':
    get:
      operationId: getSnippet
      summary: |
        Returns a snippet (e.g. page) from the text with the given `PPN` based on
        further parameters expressed in the `location` section as matrix parameters.
      tags:
        - Retrieving Content
      parameters:
        - $ref: '#/components/parameters/PPN'
        - $ref: '#/components/parameters/location'
      responses:
        '200':
          description: 200 response
          content:
            'application:json':
              schema:
                $ref: '#/components/schemas/listOfSnippets'
        '404':
          $ref: '#/components/responses/resourceNotFound'

components:
  parameters:
    PPN:
      name: PPN
      in: path
      description: |
        Specifies the ID for a text. In ZHistLex, PNDs (Pica Produktionsnummer) are used for text identification, specifically PNDs as recorded by GBV (http://www.gbv.de/).
      required: true
      explode: false
      schema:
        type: string
      example: 1001390229
    location:
      name: location
      in: path
      required: true
      style: matrix
      explode: true
      description: |
        Indicates a location within the text.
      schema:
        type: object
        description: |
          Represents a complex location specification within an individual text. All properties may be freely combined. Implementations should consider contradicting properties (such as a page number that does not correlate with a given section number) as specifications for non-existing locations.
        properties:
          page:
            type: string
            description: |
              Specifies a single page number.
            example: 67
          volume:
            type: string
            description: |
              Specifies a volume number.
            example: II
          column:
            type: string
            description: |
              Specifies a column number.
            example: 1045
          section:
            type: string
            description: |
              Specifies a (hierarchically structured) section number.
            example: 1.3.18
          canonical:
            type: string
            description: |
              Specifies a canonical reference as may be customary for specific texts.
            example: Luk 3, 4

  responses:
    resourceNotFound:
      description: The specified resource could not be found.
    unexpectedError:
      description: An unexpected error occurred.

  schemas:
    
    snippet:
      type: string
      description: Represents a single page from a text.
    
    listOfSnippets:
      type: array
      description: Represents a list of pages from a text.
      items:
        $ref: '#/components/schemas/snippet'
